server:
  port: 9040

spring:
  application:
    name: robert-monitor
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.1.111:8848

################## 邮件配置 ############################
  mail:
    host: smtp.163.com
    username: 13710011154@163.com
    password: luo123456 #登陆密码（或授权码）
    properties:
      mail.debug: false
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  #spring boot admin server config
  boot:
    admin:
      monitor:
        status-interval: 1000
        status-lifetime: 1000
      ui:
        title: 宝乐机器人云服务监控系统

      #邮件通知,记得抄送给自己（to后面加from后面的），不然554（认为是垃圾邮件）
      notify:
        mail:
          to: 632395785@qq.com,13710011154@163.com
          from: 13710011154@163.com
        routes:
          endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

  #spring boot admin login page
  security:
    user:
      name: admin
      password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

