server:
  port: 9020

spring:
  application:
    name: robot-gateway
  main:
    allow-bean-definition-overriding: true
  # kafka配置
  kafka:
    bootstrap-servers: 172.16.1.111:9092
    logs-topic: bona-logs
    # redis配置
  redis:
    database: 0 #Redis数据库索引（默认为0）
    timeout: 5000ms # 连接超时时间（毫秒）
    host: 127.0.0.1
    port: 6379
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池中的最大连接
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"   # 允许跨域请求的域名或服务器IP,多个用逗号分隔，*为允许所有
            allowedMethods:       # 允许跨域的请求方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
      #菜单模块
      - id: robot-menu
        uri: lb://robot-user
        predicates:
          - Path=/api/menu/*      
      #用户模块
      - id: robot-user
        uri: lb://robot-user
        predicates:
          - Path=/api/user/**
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true



#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

logging:
  level:
      com.bona.robot.gateway: DEBUG
      com.alibaba.nacos.client.naming: ERROR
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

robot:
  security:
    ignoresSign:
      # 忽略签名的的地址,逗号分隔
      httpUrl: >
        /api/user/login,
        /api/user/refreshToken

