spring:
  application:
    name: robot-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.1.19:3306/bona_robot?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: dev_wr
    password: KztRzKIkCD9LhDXU
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
            
# redis配置
  redis:
    database: 0 #Redis数据库索引（默认为0）
    timeout: 5000ms # 连接超时时间（毫秒）
    host: 127.0.0.1
    port: 6379
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池中的最大连接
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接    
  zipkin:
    locator:
      discovery:
        enabled: true
    baseUrl: http://172.16.6.54:9050/
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)


mybatis:
  type-aliases-package: com.bona.robot.auth.model
  mapper-locations: classpath:mapper/*.xml
  configuration.map-underscore-to-camel-case: true
    
#logger
logging:
  level:
    org.mybatis: INFO
    com.bona.robot.auth.mapper: DEBUG    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS    

#auth config
encrypt:
  key-store:
    location: classpath:fzp-jwt.jks
    secret: fzp123
    alias: fzp-jwt 

robot:
  oauth2:
    token:
      store:
        type: authJwt        